# Generated by Django 3.2.7 on 2022-04-04 03:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=100)),
                ('today', models.DateTimeField(default=django.utils.timezone.now)),
                ('discription', models.CharField(max_length=1000)),
            ],
        ),
    ]
