# Generated by Django 3.2.7 on 2022-01-02 02:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('region', models.CharField(choices=[('Local', 'Local'), ('National', 'National'), ('Reginal', 'Regional'), ('World', 'World')], max_length=100)),
                ('subject', models.CharField(choices=[('Business', 'Business'), ('Crime', 'Crime'), ('Entertainment', 'Entertainment'), ('Health', 'Health'), ('Lifestyle', 'Lifestyle'), ('Lost', 'Lost & Found'), ('Mysteries', 'Mysteries'), ('Obituaries', 'Obituaries'), ('Political', 'Political'), ('Sports', 'Sports'), ('Technology', 'Technology')], max_length=100)),
                ('text', models.TextField()),
                ('visability', models.CharField(help_text='pending, under review, approved, hidden', max_length=15)),
                ('image', models.ImageField(default='post_default.jpg', upload_to='post_pics/')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('believers', models.ManyToManyField(blank=True, related_name='post_believe', to=settings.AUTH_USER_MODEL)),
                ('nonbelievers', models.ManyToManyField(blank=True, related_name='post_nonbeliever', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
            ],
        ),
    ]
