# Generated by Django 3.2.7 on 2021-11-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_visabiliy_catagory_location_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='visability',
            field=models.CharField(help_text='pending', max_length=15),
        ),
    ]
