# Generated by Django 3.2.7 on 2022-01-02 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='believers',
            new_name='believer',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='nonbelievers',
            new_name='nonbeliever',
        ),
    ]
