# Generated by Django 3.2.7 on 2022-03-21 00:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_auto_20220101_1849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='nonbeliever',
            new_name='sceptic'
        ),
    ]
