# Generated by Django 3.2.7 on 2021-12-12 09:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='believers',
            field=models.ManyToManyField(null=True, related_name='post_believe', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='nonbelievers',
            field=models.ManyToManyField(null=True, related_name='post_nonbeliever', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='subject',
            field=models.CharField(choices=[('Bs', 'Business'), ('Cr', 'Crime'), ('En', 'Entertainment'), ('Hl', 'Health'), ('Lf', 'Lifestyle'), ('Ls', 'Lost & Found'), ('Ms', 'Mysteries'), ('Ob', 'Obituaries'), ('Pl', 'Political'), ('Sp', 'Sports'), ('Tc', 'Technology')], max_length=100),
        ),
    ]
