# Generated by Django 3.2.7 on 2021-11-14 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_visability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='visability',
            field=models.CharField(help_text='pending, under review, approved, hidden', max_length=15),
        ),
    ]
