# Generated by Django 3.2.7 on 2021-12-12 09:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_auto_20211212_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='believers',
            field=models.ManyToManyField(related_name='post_believe', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='nonbelievers',
            field=models.ManyToManyField(related_name='post_nonbeliever', to=settings.AUTH_USER_MODEL),
        ),
    ]
