# Generated by Django 3.2.7 on 2021-11-21 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_visability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='catagory',
            field=models.CharField(choices=[('Lc', 'Local'), ('Nt', 'National'), ('Rg', 'Regional'), ('Wr', 'World')], max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='subject',
            field=models.CharField(choices=[('Bs', 'Business'), ('Tc', 'Technology'), ('En', 'Entertainment'), ('Hl', 'Health'), ('Lf', 'Lifestyle'), ('Pl', 'Political'), ('Cr', 'Crime'), ('Ms', 'Mysteries'), ('Ls', 'Lost & Found'), ('Sp', 'Sports'), ('Ob', 'Obituaries')], max_length=100),
        ),
    ]
