# Generated by Django 3.2.7 on 2022-04-04 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_sceptic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='subject',
            field=models.CharField(choices=[('Annoncements', 'Announcements'), ('Business', 'Business'), ('Crime', 'Crime'), ('Entertainment', 'Entertainment'), ('Health', 'Health'), ('Lifestyle', 'Lifestyle'), ('Lost', 'Lost & Found'), ('Mysteries', 'Mysteries'), ('Obituaries', 'Obituaries'), ('Political', 'Political'), ('Sports', 'Sports'), ('Technology', 'Technology')], max_length=100),
        ),
    ]
